### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Sunjammer**
Removes references to fuse pro
Minor rewrites to better reflect current product state
Move absolute links to fusetools.com/docs to new URL

### CODE REVIEW

**Comment by kusma** [comment]
```
[ERR] 1 files had in total 2 invalid/dead links in them:
[ERR] Missing links in file basics/quickstart.html:
[ERR]  - basics/installation/setup-install-osx.html
[ERR]  - basics/installation/setup-install-win.html
Generator failed:
System.Exception: Missing links found, please correct before re-running
   at Builder.Services.OutputPath.<ApplyContentPostProcessingAsync>d__16.MoveNext() in /home/travis/build/fuse-open/docs/generator/src/Services/OutputPath.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.DocBuilder.<GenerateAsync>d__12.MoveNext() in /home/travis/build/fuse-open/docs/generator/src/DocBuilder.cs:line 66
```
Also, the files in the `api-docs`-folder are generated from the fuselibs-source, and shouldn't be edited directly. Instead, the corresponding docs in fuselibs should be updated...

**Comment by Sunjammer** [comment]
Oh jeez, that's right

**Comment by kusma** [comment]
```
$ dotnet run -p generator/src/generator.csproj -- . "https://fuse-open.github.io/docs/"
Services/ApiJsonParser.cs(69,40): warning CS0168: The variable 'e' is declared but never used [/home/travis/build/fuse-open/docs/generator/src/generator.csproj]
[INF] Starting generation of docs from root path /home/travis/build/fuse-open/docs
[WRN] Unable to find API index for fuse/triggers/iprogress - ignoring
[WRN] Unable to find API index for fuse/reactive/lettype - ignoring
[ERR] Unable to resolve seealso entry for fuse/navigation/gotoroutecommand - no match in file system nor reference map: 'ModifyRouteCommand'
[INF] adding seealso to fuse/gestures/clicked
[INF] adding seealso to fuse/gestures/doubletappedargs
[INF] adding seealso to fuse/gestures/tapped
[ERR] Unable to resolve seealso entry for fuse/elements/element/boxsizingmode/fillaspect - no match in file system nor reference map: 'Element.BoxSizing'
[ERR] Unable to resolve seealso entry for fuse/elements/element/boxsizingmode/layoutmaster - no match in file system nor reference map: 'Element.BoxSizing'
[ERR] Unable to resolve seealso entry for fuse/controls/segmentedshape/pathend - no match in file system nor reference map: 'PathStart'
[ERR] Unable to resolve seealso entry for fuse/controls/segmentedshape/pathlength - no match in file system nor reference map: 'PathEnd'
[ERR] Unable to resolve seealso entry for fuse/controls/segmentedshape/pathlength - no match in file system nor reference map: 'PathStart'
[ERR] Unable to resolve seealso entry for fuse/controls/scrollviewpager/reachedstart - no match in file system nor reference map: 'ReachedEnd'
[ERR] Unable to resolve seealso entry for fuse/charting/plot/wrange - no match in file system nor reference map: 'XRange'
[ERR] Unable to resolve seealso entry for fuse/charting/plot/zrange - no match in file system nor reference map: 'XRange'
[WRN] Unable to find API index for fuse/animation/openanimator - ignoring
[WRN] Unable to find API index for fuse/animation/trackanimator - ignoring
[WRN] Unable to find API index for fuse/animations/transformanimator - ignoring
[ERR] 1 files had in total 2 invalid/dead links in them:
[ERR] Missing links in file basics/quickstart.html:
[ERR]  - basics/installation/setup-install-osx.html
[ERR]  - basics/installation/setup-install-win.html
Generator failed:
System.Exception: Missing links found, please correct before re-running
   at Builder.Services.OutputPath.<ApplyContentPostProcessingAsync>d__16.MoveNext() in /home/travis/build/fuse-open/docs/generator/src/Services/OutputPath.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Builder.DocBuilder.<GenerateAsync>d__12.MoveNext() in /home/travis/build/fuse-open/docs/generator/src/DocBuilder.cs:line 66
```

**Comment by Sunjammer** [comment]
I didn't actually change those links, so that's weird. https://fuse-open.github.io/docs/basics/installation/setup-install-osx.html exists just fine so I guess the `basics/` part of the URL just be stripped out? Not clear to me if those links are absolute from the root dir or relative to the document

**Comment by Sunjammer** [comment]
Never mind, i'm an idiot. Stand by.

**Pull request closed without merging**
