### PR TITLE
layout: add favicon from main site

### LINKED ISSUE #34: Add favicon
https://fuseopen.com/docs/ is missing favicon. Should probably be same as on https://fuseopen.com/

### PR DESCRIPTION
**Pull request by kusma**
This isn't perfect, and depends on being hosted in a subdir of the main site.

Also, it's completely untested. It's mostly just to get the discussion started.

Fixes #34

### CODE REVIEW

**Comment by mortend** [comment]
Cool! How do we test that it works?

**Comment by kusma** [comment]
I guess by taking a dump of both sites and hosting them locally or something?

**Comment by kusma** [comment]
We could also just yolo it, what could possibly go wrong 😂

**Comment by mortend** [comment]
I second yolo. It's just one push of a button and the worst that can happen is that things just look the same as before. \*Fingers crossed\*

**Comment by mortend** [comment]
It works now, cool!

**Pull request merged**
